apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluentbit.fullname" . }}-config
  labels:
    {{- include "fluentbit.labels" . | nindent 4 }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Daemon       Off
        Parsers_File parsers.conf
        Log_Level    info

    [INPUT]
        Name              tail
        Path              /var/log/containers/network-statistics-prod-executor-*_prod_*.log
        Parser            cri
        Tag               net-stat-executor-prod
        Refresh_Interval  5
        Skip_Long_Lines   Off

    [INPUT]
        Name              tail
        Path              /var/log/containers/network-statistics-dev-executor-*_dev_*.log
        Parser            cri
        Tag               net-stat-executor-dev
        Refresh_Interval  5
        Skip_Long_Lines   Off

    [FILTER]
        Name              parser
        Match             net-stat-executor-prod
        Key_Name          log
        Parser            spring
        Reserve_Data      On

    [FILTER]
        Name              parser
        Match             net-stat-executor-dev
        Key_Name          log
        Parser            spring
        Reserve_Data      On

    [OUTPUT]
        Name              loki
        Match             net-stat-executor-prod
        Host              {{ .Values.loki.host }}
        Port              {{ .Values.loki.port }}
        Labels            job=fluentbit,app=net-stat-executor,env=prod

    [OUTPUT]
        Name              loki
        Match             net-stat-executor-dev
        Host              {{ .Values.loki.host }}
        Port              {{ .Values.loki.port }}
        Labels            job=fluentbit,app=net-stat-executor,env=dev
  parsers.conf: |
    [PARSER]
        Name        spring
        Format      regex
        Regex       ^(?<time>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}) +(?<level>[A-Z]+) +\[(?<thread>[^\]]+)\] +(?<logger>[^ ]+) - (?<message>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
        Time_Offset +0000
