apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fluentbit.fullname" . }}
  labels:
    {{- include "fluentbit.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "fluentbit.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fluentbit.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: fluentbit
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "fluentbit.fullname" . }}-config
