replicaCount: 0

image:
  repository: mysql
  tag: 8.4.6
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3306

persistence:
  size: 10Gi
  storageClass: local-path

mysql:
  rootPassword: abc123
  database: testdb
  user: dev
  password: abc123

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 512Mi

ingressRouteTCP:
  enabled: true
