---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-exporter-prod-config
  namespace: prod
spec:
  encryptedData:
    .my.cnf: AgAlc95vm28y0YNT8sBo1KM1/0IOXUsE+D31gwXcKyY/c8gRt21ULGD6puJdGNtgX8uJ3okYRQ56njVGXRIeCCEK9UMAVk5G9YLGfXjEutkplyCC8aixthLoNwUAKBP0OTuHWskmWqfe0Yn9pfwrZgafhu1Kr0KHpU4ZzN7MK2KLD7y4Cv/zWXcazytsDMyKZ8KcAGeaQOW399bB4Kngo0H2rye+nUKNy9CAuUsPCC9+wFISWtpu98rRhuY+Q6mG3evIhkzN4WhjAQ0wUSrkpG5dJsOSaC4BEABMAp45N14BnaDBMPnx7/axjCwPiQInb9dVDJp+wgfwy2QSqLaBs87QQJ3NFKHaJGauOlnTGRDvNUXbLIVTMrbQCPSs4ywxTW6zczGdLpzUzowJ78rN1oD6zUnzacXTMl297nFZEPpex/iP8OtpZydzBsZvrgWadsAyuY3+mllPXZn+VO0syN9vaw+GFXHZizPBWCRgY1B1R76PKzvqMtZFirsuCxrXYzkXJVuRQ16sobIqwLIYHYvnd6qfGwep3uhqWaSZUhN5K3syThxXXVCUnr6L7tQvP8HBSYJfyRAqou6n7LKyoA1eaShTiE6rLgXKpKKjyuwzNSxrKdlYmHYLtZBdwps6YA/8PIrY++cDQUvpxixmzCVBKVJ6KSXog1Sk+orch106HU4hosbekmVNhDdy4/O7FW/oQEFp4DaCw5ou/opAyzoW2adhE6JWj47M7Hw+lvvMWGsKoBRQiwjmamK9Z2E=
  template:
    metadata:
      name: mysql-exporter-prod-config
      namespace: prod
    type: Opaque
