apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql-exporter-prod.fullname" . }}-config
  labels:
    {{- include "mysql-exporter-prod.labels" . | nindent 4 }}
type: Opaque
stringData:
  .my.cnf: |
    [client]
    user=metric_exporter
    password=999999
