apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql-exporter-prod.fullname" . }}
  labels:
    {{- include "mysql-exporter-prod.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9104
      protocol: TCP
      name: http
  selector:
    {{- include "mysql-exporter-prod.selectorLabels" . | nindent 4 }}
