replicaCount: 1

image:
  repository: prom/prometheus
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9090

persistence:
  size: 5Gi
  storageClass: local-path

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 512Mi
