---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: liquibase-prod-db
  namespace: github-runners
spec:
  encryptedData:
    password: AgBh9its0wbhGammHHfR6XqNY2WroDHBvZjdkts9ODJZ1LOpgUINjXnmbIE7zudfPf+Ijt5LT7sJzPdj/REyBUzmZLmjUf0vMS1KVxi/aDhNIVMi8m0EGgpZVorTocLZauF3N4QnG74hZ9/qvk6U3hId2TlyDud9rxiBNj/0x7w1EeFdN6ZBIDNkzG/VjWP/jKsh/tIfMPFsYqDmQjOu2ccbYE4kz4giwyEBwhodqQwGWNuM+zh6qQ4ripmfdSHGLnmCnk2w80V+LLhptyIm4n7xoUUQ6zmp1vLr9NzuoJpHXe9qtbKpZj9QDlJlJp3J6mdZHX0Y7coPULQF7+FS+hbaS75jfFpAE9/xNxkQuh29rSxldbGrmny3umJIkg7Yv6WRuZY4G2h/yP+Cow46Y0onHyzjLgkYHkvQhPGs9ddeARaqM0t7XAQO9OTrbTHBK9VYEEkJ1o6kRopflbwTn7o8XvuW97hgPmOEnCEAkGWmj9lF4/n4qI2z5rDy2ivn2w20FkYMz7yx0vR21LMyclDv4RneO33z8q9AjFaWm/TSpXCBUbvi+p1AjHYve9w/P8cNVnhCUyZ2FN7ZCTTTEWKFOOLiWCPKfSmnWWokMLKktA0v9ioXHW8CrAzbL1k/XYB8y7+1/tkeEK7agKA0V0SN0MbaQfrGPiCAtYBbPotsQmJtJ5gqggkabWnJ5tsD2EEGa0kBO8s=
  template:
    metadata:
      name: liquibase-prod-db
      namespace: github-runners
    type: Opaque
