---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: liquibase-dev-db
  namespace: github-runners
spec:
  encryptedData:
    password: AgAhOb5xXDNnUqASh7U5mw5E8CtqdB/So9lAKEeu+OtpeUsD+K1v716J0kZUbZG/NAEo0B5ca9Ui06VwxM/S8NXlH/c2nSZEQNm9XreCP9bCGyfQyz00itNK+0jrsHl0ODUljTKYHW29h7/oyyFKK8KNBydbqixcsrf/9qL2J1tJ4u/ypLY6nQlbwxu/trYvsCk0ogF1eWEWBiGxRNOJ+2gwXpVSFzlx2nEGi4I2Ok0UljLsS8NE7g2NqF8Qqyxp+6RYsEkagy3ObRiLf+oqk4ItpYiFERyGRGqg1NskS7KpphkG2eOeOffRSZ11TdVpFaFRiePxAGpOUVBF12pZNF0mGY0E0UE0jBRXFnsp/aD10d0wi/anx3c49fsqZ+RMSIhWZvWBYKw5PiZ+3I8ItVT66zWm4iLgx35h/GzATyatPs/r3ObNIn2gIRVYGghY+xiu+MgZHT7lR/TmldtIGBqdswi536ihVVg67lYlqy80G0ll5MGQqbzrRfbpr1JP0gCCEytRujMtOVGbwt9a5a0zA0OmiNqcfQPqBI4F6M8S3sHkH1yD/+LvVD3PulaWFaHnHHBDvUPIGx64d8VC7CpLey7vxatZwd3kIatwa4gHN7EYYym3RG/nYDBkPoIZDVjcyKUgY+XCCksrXB9yXuH02EYLOLI/07ZNUNCFNAXQTMEBNp5LlxjdBCHfsv6RNoAnqt6BfxM=
  template:
    metadata:
      name: liquibase-dev-db
      namespace: github-runners
    type: Opaque
