---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: arc-github-config
  namespace: github-runners
spec:
  encryptedData:
    github_token: AgBH1KlcXnbn3x+UxbjYbKPaTbOTj8CWTCP8IRN3Q4LKVHJaStRnpObkl9r5Zu7/YKvGLgLk/gheLpGYmwa+Ph15wg0x0K7KDOvBen9vVrDMvnbz4IMERHrUGvZWvnIDXsbzySQqFliWKK1su6y3muj5PC1kHQ/W3EQ2/SdJy7urhp6657jKPp3SzjCapNgqobLYdVUfH5E4e+4OtlNHMizYjZkdk0lInV6jglTekfqOOK1F2+dtKc8bUaXjU3Phlh1ptvwOTMmW3LsebI3KOopFGj9eAbf6dwo+fsourgTKH61TJT17isE8+7l0NTS4ZzGuK2jpirLj0kK8Mnyz3K5ycMnoI34JwxZ3bMOgxPUr8w6q+6uxo+/QsgGNLilE6Af5ktgAMjR6HAIZEabSU+8apHqgWZx3+eCEqc1m6sdyh5JW3vBlguSEQVaWp2PiAXAtCx/uLDoZC71nOuvvrMjSsyxwzr4/uvzoqZS3Q5Nk8tpBUFneB8TiQnCG8QRoE1grKZCX39+Db8nIy/kWIlNMiEgvqf+cTvKCiC2U225XETRqsNc4pt8uKuS4oCq87MA0CXGM9OZaUS+HjN4Sz8hCwIaln8ETWIZEGvaElmVXvNU7bCImtDblTsiGnfTxpOOMmst2b08zEebERRfVa354ElJS2yvwn0coxv9Vuh8JtlRcDc45fGxSPeLWuik3KY6qrJSgNouf+4jTzsPrEr1lv+bIEA6oExqDM1g+dZ5MRSM90qoD4Ell
  template:
    metadata:
      name: arc-github-config
      namespace: github-runners
    type: Opaque
