apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "network-statistics-prod.fullname" . }}-admin
  labels:
    {{- include "network-statistics-prod.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "network-statistics-prod.selectorLabels" . | nindent 6 }}
      role: admin
  template:
    metadata:
      labels:
        {{- include "network-statistics-prod.selectorLabels" . | nindent 8 }}
        role: admin
    spec:
      imagePullSecrets:
        - name: {{ include "network-statistics-prod.fullname" . }}-ghcr-secret
      containers:
        - name: admin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.adminPort }}
              protocol: TCP
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prd-admin
            - name: SPRING_DATASOURCE_QUARTZSCHEDULER_JDBCURL
              value: "jdbc:mysql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.quartzDatabase }}?connectionTimeZone=UTC"
            - name: SPRING_DATASOURCE_QUARTZSCHEDULER_USERNAME
              value: "{{ .Values.database.quartzUsername }}"
            - name: SPRING_DATASOURCE_QUARTZSCHEDULER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "network-statistics-prod.fullname" . }}-db-secret
                  key: quartz-scheduler-password
            - name: SPRING_DATASOURCE_STATISTICDB_JDBCURL
              value: "jdbc:mysql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.statisticDatabase }}?connectionTimeZone=UTC"
            - name: SPRING_DATASOURCE_STATISTICDB_USERNAME
              value: "{{ .Values.database.statisticUsername }}"
            - name: SPRING_DATASOURCE_STATISTICDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "network-statistics-prod.fullname" . }}-db-secret
                  key: statistic-db-password
          resources:
            {{- toYaml .Values.resources | nindent 12 }}