apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "network-statistics-prod.fullname" . }}-executor
  labels:
    {{- include "network-statistics-prod.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "network-statistics-prod.selectorLabels" . | nindent 6 }}
      role: executor
  template:
    metadata:
      labels:
        {{- include "network-statistics-prod.selectorLabels" . | nindent 8 }}
        role: executor
    spec:
      imagePullSecrets:
        - name: {{ include "network-statistics-prod.fullname" . }}-ghcr-secret
      containers:
        - name: executor
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.executorPort }}
              protocol: TCP
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prd-executor
            - name: LOGGING_FILE_NAME
              value: /logging/network-statistics-log1/executor.log
            - name: SPRING_DATASOURCE_QUARTZ_SCHEDULER_JDBCURL
              value: "jdbc:mysql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.quartzDatabase }}?connectionTimeZone=UTC"
            - name: SPRING_DATASOURCE_QUARTZ_SCHEDULER_USERNAME
              value: "{{ .Values.database.quartzUsername }}"
            - name: SPRING_DATASOURCE_QUARTZ_SCHEDULER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "network-statistics-prod.fullname" . }}-db-secret
                  key: quartz-scheduler-password
            - name: SPRING_DATASOURCE_STATISTIC_DB_JDBCURL
              value: "jdbc:mysql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.statisticDatabase }}?connectionTimeZone=UTC"
            - name: SPRING_DATASOURCE_STATISTIC_DB_USERNAME
              value: "{{ .Values.database.statisticUsername }}"
            - name: SPRING_DATASOURCE_STATISTIC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "network-statistics-prod.fullname" . }}-db-secret
                  key: statistic-db-password
          volumeMounts:
            - name: logging
              mountPath: /logging
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- if eq .Values.logging.volume.type "emptyDir" }}
        - name: logging
          emptyDir: {}
        {{- else if eq .Values.logging.volume.type "hostPath" }}
        - name: logging
          hostPath:
            path: /logging/network-statistics-log1
        {{- else }}
        - name: logging
          persistentVolumeClaim:
            claimName: {{ include "network-statistics-prod.fullname" . }}-logging-pvc
        {{- end }}