{{- if .Values.ingressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "network-statistics-prod.fullname" . }}-admin
  labels:
    {{- include "network-statistics-prod.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/prod/network-statistics`)
      kind: Rule
      middlewares:
        - name: {{ include "network-statistics-prod.fullname" . }}-strip-prefix
      services:
        - name: {{ include "network-statistics-prod.fullname" . }}-admin
          port: {{ .Values.service.adminPort }}
{{- end }}