---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: network-statistics-prod-db-secret
  namespace: prod
spec:
  encryptedData:
    quartz-scheduler-password: AgAgl+vscqqt1uD3JAkQI4bdD2wZ8mWNFbgxRay9dBY4f8/EUey6Yrv0ditOnUzwDQDzWln1nsR5m7lvt9okqrSW3IOsvEZs7mbbydeAabtWLY0czqpY7BNHHw2IapjKp1lW/rKIXNqIOptj0oEGFEB6EG9QeNBa6NJLIsIdhSoUx8gVGYcSKBieHvEO2MJ8EtpAMlFwltg8AQAJ2lD4U7uUwOoamdiLv5gXQqwfEl3JIcI1nZtgh1DqyALsc8sWWFNgKbb0yg9c3isDLJk5VKO5l8Xb5F0sUeDpy00Z2FH69ORVgsDznOM0ceUIM46ccOiCCZuhP6SAgLqGPyudQKNGvdSLO1Pg2IZ0G9cweLUcEEUb5MO2mq+kpQ9TgxQp2RhNJtdBY8zPoESuvWA5R5x1A3sg8nLKmWbZpNIE2sx4NdTOZ75ln3v5/OAbmKVVlQI31A96Xm2hoRqEdz8w8X9GDofJl41ypT+IL7QW1pfCjE9MS/DNx82+DkBOHcydnykNeTFmPKUAPBLdSOJDogRsX303FB4LQP4Zpvhgws0fAb0+mTS6Fh3SVgRYw1K+fCvIFLvVWqkM8/HyuSgzHqaI2DiFYtuezmGXgXq3bvx8m+sJxNiT6Zk1AKMOJ3CG86Xk7tLBVNlB9YwQ0qniL9oIYqPX0tLI0xNGbpVDXEGyvdLXdW/6m6/1nIQ2hFzMbkan4zVXCUI=
    statistic-db-password: AgCOIejLhMF9MQq4aKgm/8vi49sd6jhrjha+RU4unISoBH3SZQaSlEifXP6BuHYYNF72ZIPiX5QVKE2JIoGeBK6eRi1a809lcLs+0EyOkSjf6Q8UOkkUIuserD9m4Cac7stT/d8VDzc/dHCxdwhvuN6cKv5W4nQU5bofLrDtQ5eYO1y/piTBxuYtQBtaw086tU5tELixPZZyttw5FZuRB12n5h71vrtUUeYilhFqeq4ZQldQIdww54tkkb2eLjmQwYovdZdAjgjXg6FPiC1VeTKonJ4uPzgKFtJ08o4TgNbDEGtZk+RFkElVgjqsswEONgcBrcc++RD3DpeyY2lJWKMXQGwVmuXzE+HXKgVPmaN1geavMKpDjAxzezn3rLNYxnPpaKwqqZh7pJ9Sx6Z/q6DLMMcrAbAEceb5ofk4bHZPKNzeE9AChptQ92DJN2MKqQ9rNxR48a6GisnlyOO/S+s5dwDbBxViJZX072KwvxZME/bYYazy3gyTAUIHiDD50qXd9iJYNzFVb6fn72OLNzNU5OvrINSprLiMYULJ4ZTGXfg0abUWFptfF6iRXhP92Tq8D1Gi4SEFXg6J5mRSPjWmDqASB/9KzroF68NPGfbPEodH9J2fcTZgSpT0jzuwOw+K40qvPib6Dy1Go9OQTLKpiv8ZDoV55427HW0BXhyezXQz8J3/Jn7cei8ieCImAOuHo0qzYJM=
  template:
    metadata:
      name: network-statistics-prod-db-secret
      namespace: prod
    type: Opaque
