---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: network-statistics-prod-ghcr-secret
  namespace: prod
spec:
  encryptedData:
    .dockerconfigjson: AgB8SX7aWFq9iqc1fjhbA6sF1S8GumUCyttf9taIfLq5unHd6unU1ilDZeUlRqII/NgIGWEPD/6UE70XSdr4erHKgzuTHL7naPjsKcuehrlcBQk5xqwmOQYn3fMGZnhgC5jHE2jPBkqwk+9On+mV3HGpHmwu/YRUyveJoQzHauVhqvZTX+I143BJeWkI4HSgqLW9BcSRVydJnUmgRt0HfBWHXVJtbGiL537npzxJq2QXLs68lrQ+my+bxwLUy+6p9HAGukOIwuWonIGWEOZAKjyGHoGTwA70rxcO3WJJq1N0f+AbQDrv/aLCCwZsn2P2uoQ42M0yU0q6NQxTk5RVgJFyK5nxXW5dDbSo7ROZictBROufOssKk2j5FaVi2EMExgIytJXuy/pvzL5c8Qc1xgzZ5x1GaYXV9MvFC3nwMZrxWv5PuDuYjX7w2BNoXEY6QT9sqxxBQR1vKw7psu7YTeCw4spBpMayV2xuxFT/Z+UOqk8FAb8InK5wsZ1yRdbYBZezhqA0uQ4x3FBhLDHOuY36mPKkg6riL3HBLSLo58iE6Yyi8F0wmkuIsm3qODCoC/T2htgQERtNHdupJxZdVj9nVajuUccowSeWIynVLKig/vj69JTsgKiKQhW4w04xb9cKh1K/5dyi9XzqNa3gIiXX7AZMUJ56aRG42mb2A618zZcFNgaXTGO33XZqzLReB5JC26H9ryDmuf7q/RchryazM5xYEgNJ2dlVXcqezKOTfAw3996SuOiWWlMtMiPsQ9iGLUw5f2fi/scd1mgtkSSVavSnVILSXVawI1dYzCA+k1su3kleFwiyX/cyPQzzD5ZX3PMRvw1xBOmz4m783O9HB5UCr1KM0/Y0zpnjqPpdhArGnZ8ypGfuNnFcTp4t1TAkCApacjhdaYmM7hLKYcRu0V0geWey7fId9VTPgDR33k8=
  template:
    metadata:
      name: network-statistics-prod-ghcr-secret
      namespace: prod
    type: kubernetes.io/dockerconfigjson
