apiVersion: v1
kind: Secret
metadata:
  name: {{ include "network-statistics-prod.fullname" . }}-db-secret
  labels:
    {{- include "network-statistics-prod.labels" . | nindent 4 }}
type: Opaque
stringData:
  quartz-scheduler-password: {{ .Values.database.quartzPassword | quote }}
  statistic-db-password: {{ .Values.database.statisticPassword | quote }}