apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      mysql-prod:
        port: 3306
        expose: true
        exposedPort: 3306
        protocol: TCP
      mysql-dev:
        port: 3307
        expose: true
        exposedPort: 3307
        protocol: TCP
