apiVersion: v2
name: k8s-gh-runner
description: General-purpose Kubernetes GitHub Actions runner (ARC) + secrets
type: application
version: 0.1.0
appVersion: "0.14.2"
dependencies:
  - name: gha-runner-scale-set
    version: 0.14.2
    repository: oci://ghcr.io/actions/actions-runner-controller-charts
