apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mysql-prod.fullname" . }}
  labels:
    {{- include "mysql-prod.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mysql-prod.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mysql-prod.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mysql-prod.fullname" . }}-secret
                  key: root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "mysql-prod.fullname" . }}-secret
                  key: database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "mysql-prod.fullname" . }}-secret
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mysql-prod.fullname" . }}-secret
                  key: password
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: config
              mountPath: /etc/mysql/conf.d
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "mysql-prod.fullname" . }}-data
        - name: config
          configMap:
            name: {{ include "mysql-prod.fullname" . }}-config