replicaCount: 1

image:
  repository: grafana/fluent-bit-plugin-loki
  tag: 3.5
  pullPolicy: IfNotPresent

loki:
  host: loki
  port: 3100

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
