{{- if .Values.imagePullSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "network-statistics-dev.fullname" . }}-ghcr-secret
  labels:
    {{- include "network-statistics-dev.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "network-statistics-dev.imagePullSecret" . }}
{{- end }}