{{- if .Values.ingressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "network-statistics-dev.fullname" . }}-strip-prefix
  labels:
    {{- include "network-statistics-dev.labels" . | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      - /dev/network-statistics
{{- end }}
