---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: network-statistics-dev-ghcr-secret
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgBKKnwrZcQ4HRncMMOIVCMCz+wzTALbIMFZk5uvuME9gidpEnlEwRKIMOT8UCwOvsY/kxI/002kdM4CmZ8cEzYC4xxmITNy5kuCVgGBeFom7r8WdEQ0sesfx2EaRO8E/try+Bkas9UVy1WfNyAxxS3hQYV1E//9LFNsUiRzDVANp7Pdz8IeosbP6mD2tszivRTcF0zPr/z4FWQrXtDJuxApHlRNEn4tpg5C17HAj5QsTaNZLExZanPpNtgUVdYyUWiX6ZQT2vth7bemT1/f3dyLaJVX+uBkqu2HR3knAqza9xxM5vfwtLOCkMPetwKguABA0PlWwsNbHNBfCeHNwH4cWT+cc+P9+Rt6Z9R52h8iNSVFcYhhvLtr6vNK41LACQtyTjzJOLD+zoMyOS/q8lnOun7NlhP8feLfRpI5VMS2GLGcUmVekIt4ZEiJldKEkioY3yuhVtAOsAClDCpxfE7O0Cq5mtw5aj5IAaFEq+NbouryX7nqUeQ7ff7WueGtSvIFLNeAnnvnT5LgHp+gNvyTcetlueVywuuEg444DDQ05qBIwVXT+o/XCJhrgexijjx+GV3Mtga903dGiWbmkDxwtBeAIIDToTy/oylCqhrNXc9jlyASNYF9WO/C+7EgEqA+d14CYkvowIbG4UjdjbxsSVuNmzjzOg2QbjMu93mKF9RLmx8XzLBVIIDeVkLWFPZxhStvblrChAxsoJrnRBwIe4kkLoTH7K29tI83LX7eMumZXY0XzbH8ECcGDe+pKn3W2hNjR3YE59Q0mNXo03UFGtwayVtnmQhaK64D30NnIibgHdXA5r+v7xbaAcNo0Kp1dHTM+umMInDEDBCCorTPSHxXzv6tDQZesh4XDqncZUU7j+p9uukybiozs1NmbysYlo8kMw7Ir0hk0w0ree1W6pIPwUZcpQhTnm366pSD02A=
  template:
    metadata:
      name: network-statistics-dev-ghcr-secret
      namespace: dev
    type: kubernetes.io/dockerconfigjson
