---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: network-statistics-dev-db-secret
  namespace: dev
spec:
  encryptedData:
    quartz-scheduler-password: AgBCqNxkQDbiipG6q8pJS65NUMot+dPB6CSvZNW+JYOsdRVfJsQwEdoFU8H/L0VTRwiXf4Q3BlIBNyM/JpWF5eWpre2p3AUFwdH3UzmpjmEX7riQmR9/he7vNzM9irhKo1VzQ88Ru6gJ9ciM2MEb4wlyRMcY0ulK709bfE/tHljrKBMXF9xEKvQ7GVM1olk/Rroihi2xj4eRURRyrMzLPXMCrfkGJ2zSZQmJcKbWJ/6mLJUJTnrbzQMjap1hGjvZPx8og3vBVYwLM7oj7zOfFABiyxoJrwt5wRdXK3yOdJGW4S/JXM96NTwWkPTG7Zuccq0OtvAu0qDkqBLp6Vg50n4T4mQUANsnOJUKpyuNLldhS5xdo25oJqFv8blcQv97eCoB8Ej1jZdAJrvJFNCvmbG1F4HDj/9QeF6XcAsHSyd1gUsyWy44PgZZgJfQkb7Dq3+LSA+aWm7KHRwDkEW1X8Z8swR7CvK5PgAyUtIfqYH4fkOEm9fOF41aW5g5t4pUjkni60bAOFSrqXxIvqVyavQ3yad65VCfi4kg4YQBA04HOj5IQGvu/ceKuaixZyJXzEep9JCkqjUIUlv8LxZOrGhBuCTpXS9pmwb0mX6NEWv/Qer9vjzgx7784wkeO84aPRoEUHTHx1smpazhWbkbeX5S7buFrqVOp3eeGgRQjySD0vJjjGuUSV6CpVH25LlAh0btc5osR4U=
    statistic-db-password: AgAy2KjCE4Nad27nte3bUGX2tBCOi0oQqPnDFlP3F3n3vO11mmEc8/OpxFMfvjA0EPzqCl8nsgb2IQ9pzpN29WI5NzD8iJyQ2AuDU+lgLe3Arjnc4X41bVk3UzXRK/+RG9Um3P+mQ+0XSkD4Vtee8IhYyuHm2hin/H5YvPnQ9HzwHkDkzqRlsGjn3ckxZhPcd+bWSrYpz+Ex2f5rlKwX87N/q9YP5H5D8kC/6S2XH6X6COVDBy0r6JZYbTCBs9j0I/lv+RFlhGkLztSz1lusC+D2tFrNu1XMlpX2d9OW6+9yBnu7nQLlxvUmtSJN/4gu4xLnvvZ/J6g5IIp8bnKeb5DYzig8Gk2xdX4NpS32fzJA9ScAx2jmuKlnzRlM+GN+7qdmmkEYvcr3m49f2P4a+9RZyadEGJvEZr4GrCOt5GXRyBh45O0QQNS6jmfMSuVuuyZIc2Xh4LSLGRJSUIcrlhHMvKzGkXJ+1XBxMAwc1xNit88gS2unrhn2o1vzs1hUUQ3F/MxrRTYOWXVe1VoZwxV7Hy6Bo8FzHt2opvCqr+GVNiuRs4nHd+5YbZRCc+HL5GwmFfTAWAE8jL7p0XVofhvgJyhrJHthQPQgmazKqXV/QsSMWKCDVO4dW1G1aHCuWB0MtnbIQHHC3ADS+dZuG0qkYBv3Cg0EqYmnc1+PBeeHjPhXiu1VIflseOZ0zdpdbZWU9brp7n4=
  template:
    metadata:
      name: network-statistics-dev-db-secret
      namespace: dev
    type: Opaque
