{{- if not .Values.database.useSealed }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "network-statistics-dev.fullname" . }}-db-secret
  labels:
    {{- include "network-statistics-dev.labels" . | nindent 4 }}
type: Opaque
stringData:
  quartz-scheduler-password: {{ .Values.database.quartzPassword | b64dec | quote }}
  statistic-db-password: {{ .Values.database.statisticPassword | b64dec | quote }}
{{- end }}
