apiVersion: v1
kind: Service
metadata:
  name: {{ include "network-statistics-dev.fullname" . }}-admin
  labels:
    {{- include "network-statistics-dev.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.adminPort }}
      targetPort: {{ .Values.service.adminPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "network-statistics-dev.selectorLabels" . | nindent 4 }}
    role: admin