apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "liquibase-runner.fullname" . }}
  namespace: github-runners
  labels:
    {{- include "liquibase-runner.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      {{- include "liquibase-runner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "liquibase-runner.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 120
      containers:
        - name: runner
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: REPO_URL
              value: {{ .Values.runner.repoUrl | quote }}
            - name: RUNNER_NAME
              value: {{ .Values.runner.name | quote }}
            - name: RUNNER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: liquibase-runner-pat
                  key: token
            - name: RUNNER_LABELS
              value: {{ .Values.runner.labels | quote }}
            - name: RUNNER_WORKDIR
              value: {{ .Values.runner.workDir | quote }}
            - name: EPHEMERAL
              value: {{ .Values.runner.ephemeral | quote }}
            - name: DEV_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: liquibase-dev-db
                  key: password
            - name: PROD_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: liquibase-prod-db
                  key: password
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
