---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: liquibase-runner-pat
  namespace: github-runners
spec:
  encryptedData:
    token: AgAqGZ4zIZ4KHw9/0ahzD8x73MKg1fQxFHgUjCrozjWludorcin74D0CvmyYXzveiD3karw3yvcF2Bbd9bg5Kv/93rQ+PnFtzrMEB/UdYtP/Jdj45hB3Tnf83Y3LAa8zsw/kQm1JfuulQNbZmfWtUtRzNN+ukGWMGC+0VYZYqH78Tu2Uou4gLQpzPWv5srnd1i8ozivKrf63bhpxAihwoF0j0S3zU24uEIq/fvRE4pKk5SrcWOncIAphGeeKP6jdrBnus6RGxnQ9AJjeZ0RSb+5kvxsceaU+1P78JXUT2T9D2cK5v/loCMgqtmRazorLnJLdj8hupZFYT1vBAU+KDB3skyrVZw3z9MYlPSTwUvg8ZdU3NkKCHSSDg4Hn9FCJMvp0VzqE4JA5Ph3iKmJqh26sWj1JFUAn71rjsOmrzY1Ja95vDYodj8SSXnW1jYdDjOPPBkXyB6Opyqc6KpbewO3gMXxVQLp7gYQ/eNmFDgdfVJwTFMQBix/qaSr9WH8pSqcmV8nP23piuvWmMPjHAB8GYkorO9PIfDG5JQO0NTxaFDuP8GlCnFZB9aKvDA793rjEavvxvlPaTVGMH96euYkJMxMRDVyvdJTtLLN7KB9icssKnX3UO31YGqmZYMAlxL62ctWiF8XVRmRTcCKlKMNYQc5CqCJRWdWbJv9A0YqObhufnnC4k7V0nu0w0qKqYozfFP20djisSI3rNO4Z6Mv6dtoq4KAqumYq8V/cwUULiho2W8VvO1eC
  template:
    metadata:
      name: liquibase-runner-pat
      namespace: github-runners
    type: Opaque
