apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "loki.fullname" . }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "loki.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "loki.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: loki
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -config.file=/etc/loki/loki-config.yaml
          ports:
            - containerPort: 3100
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /loki
            - name: config
              mountPath: /etc/loki
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "loki.fullname" . }}-data
        - name: config
          configMap:
            name: {{ include "loki.fullname" . }}-config
