apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-gh-runner
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/minhntt1/local-infra
    targetRevision: main
    path: helm/k8s-gh-runner
  destination:
    server: https://kubernetes.default.svc
    namespace: github-runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
