apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-config
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    alerting:
      alertmanagers:
        - static_configs:
            - targets:

    rule_files:

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]
            labels:
              app: "prometheus"

      - job_name: "mysql-exporter-prod"
        static_configs:
          - targets: ["mysql-exporter-prod.prod.svc:9104"]
            labels:
              app: "mysql-exporter-prod"

      - job_name: "network-statistics-executor-dev"
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ["network-statistic1.dev.svc:8080"]
            labels:
              app: "network-statistics-executor-dev"

      - job_name: "network-statistics-executor-prod"
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ["network-statistics-prod-executor.prod.svc:8080"]
            labels:
              app: "network-statistics-executor-prod"
