apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql-dev.fullname" . }}-secret
  labels:
    {{- include "mysql-dev.labels" . | nindent 4 }}
type: Opaque
stringData:
  root-password: {{ .Values.mysql.rootPassword | quote }}
  database: {{ .Values.mysql.database | quote }}
  user: {{ .Values.mysql.user | quote }}
  password: {{ .Values.mysql.password | quote }}
