replicaCount: 1

image:
  repository: grafana/loki
  tag: 3.5.6
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3100

persistence:
  size: 5Gi
  storageClass: local-path

loki:
  config:
    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h
    ingester:
      wal:
        dir: /loki/wal
      max_chunk_age: 1h
      chunk_idle_period: 30m
      chunk_retain_period: 1m
    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/cache
    compactor:
      working_directory: /loki/compactor
      delete_request_store: filesystem
      retention_enabled: true

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
